name: bahdan-ecosystem-infra

services:
  caddy:
    image: caddy:2.10-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../portfolio/public:/srv/portfolio/public:ro
      - ../ileza/public:/srv/ileza/public:ro
      - ../stackhal/public:/srv/stackhal/public:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal_net
    depends_on:
      - portfolio-app
      - ileza-app
      - stackhal-app

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: "bahdan_prod,ileza_prod,stackhal_prod"
      POSTGRES_USER: ${DB_USER:-bahdan_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_me_in_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh:ro
    networks:
      - internal_net

  portfolio-app:
    build:
      context: ../portfolio
      dockerfile: Dockerfile
      target: app
    restart: always
    environment:
      APP_ENV: prod
      APP_SECRET: ${PORTFOLIO_APP_SECRET}
      DATABASE_URL: "postgresql://${DB_USER:-bahdan_admin}:${DB_PASSWORD:-change_me_in_prod}@postgres:5432/bahdan_prod?serverVersion=17&charset=utf8"
    networks:
      - internal_net
    depends_on:
      - postgres

  ileza-app:
    build:
      context: ../ileza
      dockerfile: Dockerfile
      target: app
    restart: always
    environment:
      APP_ENV: prod
      APP_SECRET: ${ILEZA_APP_SECRET}
      DATABASE_URL: "postgresql://${DB_USER:-bahdan_admin}:${DB_PASSWORD:-change_me_in_prod}@postgres:5432/ileza_prod?serverVersion=17&charset=utf8"
    networks:
      - internal_net
    depends_on:
      - postgres

  stackhal-app:
    build:
      context: ../stackhal
      dockerfile: Dockerfile
      target: app
    restart: always
    environment:
      APP_ENV: prod
      APP_SECRET: ${STACKHAL_APP_SECRET}
      DATABASE_URL: "postgresql://${DB_USER:-bahdan_admin}:${DB_PASSWORD:-change_me_in_prod}@postgres:5432/stackhal_prod?serverVersion=17&charset=utf8"
    networks:
      - internal_net
    depends_on:
      - postgres

networks:
  internal_net:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
