<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260905140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create ai_interactions table for privacy-preserving AI and MCP telemetry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(
            'CREATE TABLE IF NOT EXISTS ai_interactions ('
            . 'id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, '
            . 'occurred_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, '
            . 'type VARCHAR(32) NOT NULL, '
            . 'identifier VARCHAR(128) NOT NULL, '
            . 'path VARCHAR(255) NOT NULL, '
            . 'visitor_hash VARCHAR(64) NOT NULL, '
            . 'PRIMARY KEY(id))'
        );
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_ai_interactions_occurred_at ON ai_interactions (occurred_at)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_ai_interactions_occurred_type ON ai_interactions (occurred_at, type)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_ai_interactions_occurred_ident ON ai_interactions (occurred_at, identifier)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_ai_interactions_occurred_path ON ai_interactions (occurred_at, path)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS ai_interactions');
    }
}
